
# 서문 {.unnumbered}

코딩은 챗GPT로 대표되는 인공지능 시대에 필수적인 기술이다. 본 책 "챗GPT 코딩"은 프로그래밍의 기본 개념부터 실무에서 활용할 수 있는 다양한 도구와 기술까지 폭넓게 다룬다. 특히 챗GPT와 같은 최신 AI 기술을 자유자재로 다루기 위해 꼭 필요한 기본기를 상세히 설명한다.

책의 앞부분에서는 프로그래밍의 기초인 변수, 조건문, 반복문, 함수 등의 핵심 개념과 함께 데이터 과학, 기계 학습, 딥러닝, 나아가 생성형 AI의 기반이 되는 문자열, 파일, 리스트, 딕셔너리, 데이터프레임 등의 자료구조를 기초부터 다루고 있다.

이어서 프로그래밍과 불가분의 관계인 버전 제어에 대해 다룬다. 버전 제어를 대중화시킨 Git을 소개하고, Git의 기본 사용법부터 GitHub를 통한 원격 작업, 협업, 충돌 해결 등 실무에 필요한 기술을 자세히 안내한다. 공개 과학 기술 및 협업 과정에서 필수적으로 따라오게 되는 공개 과학, 라이선싱, 호스팅, 출처 표시, 통합 개발 환경 등도 소개하고 있다.

후반부에서는 정규표현식, 네트워크 프로그래밍, 웹서비스 활용, 작업 자동화 등 실무에서 유용한 도구와 기술을 소개하고, 마지막으로 챗GPT를 프로그래밍에 어떻게 활용할 수 있는지 설명하며, 코딩에 대한 새로운 시각을 제시한다.

본 책을 통해 프로그래밍 전반에 대한 이해를 높이고, AI 기술을 활용한 프로그래밍 작업의 생산성을 극대화할 수 있을 것이다. 지금부터 새로운 코딩 여정을 시작해보길 바란다. [^cover]

## 책의 구성 {.unnumbered .unlisted}

이 책은 통계 및 데이터 사이언스를 염두에 두고 프로그래밍을 처음 접하는 독자들을 위해 기획되었다.
특히 디지털 전환 시대 갈수록 중요성을 더하고 있는 통계 및 데이터 사이언스 분야에서 코딩에 중점울 두고 집필을 진행하면서 저자가 그동안 깊숙이 관여한 "소프트웨어 카펜트리"[@gonzalez2019software], "정보과학을 위한 파이썬"[@severance2015python], "챗GPT 데이터 사이언스"[@lee2024sql; @leeshin2023; @lee2024quarto]를 기반으로 작성되었음을 밝혀둔다. 이 책은 총 4부로 나누어져 있으며, 각 부는 프로그래밍의 기초부터 실제 활용까지 단계적으로 설명하고 있다.

1부 "프로그래밍"에서는 프로그래밍을 학습해야 하는 이유와 함께 변수, 표현식, 문장, 조건부 실행, 함수, 반복 등 프로그래밍의 기본 개념을 다루고 있다. 이를 통해 독자들은 프로그래밍의 기초를 탄탄히 다질 수 있고 실제 R과 파이썬 프로그램을 직접 작성하고 테스트할 수 있다.

2부 "자료구조"에서는 문자열, 파일, 리스트, 딕셔너리, 데이터프레임 등 다양한 자료구조를 소개하고 있다. 자료구조는 데이터를 효율적으로 저장하고 관리하는 방법으로, 프로그래밍에서 매우 중요한 역할을 한다. 모든 자료구조를 다루지 않고 꼭 필요한 것만 선택하여 설명하였다.

3부 "버전제어와 협업"에서는 Git을 이용한 버전 관리와 GitHub을 통한 협업 방법을 설명한다. 이를 통해 독자들은 효과적으로 프로젝트를 관리하고, 다른 동료 개발자, 과학기술 연구자들과 협업하는 방법을 배울 수 있다. 코딩을 혼자서만 하지 않고, 디지털 전환 시대를 넘어 AI 시대 다른 동료와 함께 협업하여 프로그램을 작성하는 방법과 연관된 지식을 학습하게 된다.

4부 "분야별 코딩"에서는 1~3부에서 학습한 기초를 바탕으로 정규 표현식, 네트워크 프로그래밍, 웹서비스 API 사용, 데이터베이스와 SQL, 작업 자동화, 시각화 등 다양한 분야에서의 프로그래밍 활용 방법을 살펴본다. 또한 최근 주목받고 있는 챗GPT를 활용한 코딩 방법도 다루고 있다.

이 책을 통해 독자들은 프로그래밍의 기초를 다지고, 챗GTP로 대표되는 AI시대 실제 활용 방법을 배움으로써 프로그래밍 실력을 향상시킬 수 있을 것으로 기대되고, 또한 버전 관리와 협업 방법을 학습함으로써 챗GPT와 같은 AI와 함께 동료 개발자들과 협업하여 다양한 방식으로 프로그램을 작성하는 방법을 배울 수 있다.


::::: {.content-visible when-format="pdf"}
::: callout-note
### 소스코드와 실습 환경

챗GPT 코딩 책 집필에 사용된 모든 소스코드, 데이터, 이미지는 GitHub 저장소에서 확인할 수 있으며, 
쿼토로 작성된 본서에서 직접 실습도 가능하도록 제작되었다.

🌐 웹사이트: https://bit.ly/48V8u1T

💻 소스코드: https://bit.ly/48RqMB9

:::

:::::

